export const COMBOS_GET_REQUEST = 'COMBOS_GET_REQUEST';
export const COMBOS_GET_SUCCESS = 'COMBOS_GET_SUCCESS';
export const COMBOS_GET_FAILURE = 'COMBOS_GET_FAILURE';
export const ADD_COMBO_REQUEST = 'ADD_COMBO_REQUEST';
export const RECEIVE_COMBO_SUCCESS = 'RECEIVE_COMBO_SUCCESS';
